<?php

include 'templates/head.php';


?>

<style>
    .left-12{
        margin-left: 12px;
    }
</style>

<body>

 <!-- ===============>> Preloader start here <<================= -->
 <!-- <div class="preloader">
   <img src="assets/images/logo/bobis.png"  width="100" alt="preloader icon">
 </div> -->
 <!-- ===============>> Preloader end here <<================= -->



 <!-- ===============>> light&dark switch start here <<================= -->
 <!-- <div class="lightdark-switch d-none">
   <span class="dark-btn" id="btnSwitch"><img src="assets/images/icon/moon.svg" alt="light-dark-switchbtn"
       class="swtich-icon"></span>
 </div> -->
 <!-- ===============>> light&dark switch start here <<================= -->




<!-- ===============>> Header section start here <<================= -->
<?php include 'templates/navigation.php'; ?>
<!-- ===============>> Header section end here <<================= -->




 <!-- ================> Page header start here <================== -->
 <section class="page-header bg--cover" style="background-image:url(assets/images/header/1.png)">
    <div class="container">
      <div class="page-header__content mt-5" data-aos="fade-right" data-aos-duration="1000">
        <h2>Terms of Services</h2>
        <nav style="--bs-breadcrumb-divider: '/';" aria-label="breadcrumb">
          
        </nav>
      </div>
      <div class="page-header__shape">
        <span class="page-header__shape-item page-header__shape-item--1"><img src="assets/images/header/2.png"
            alt="shape-icon"></span>
      </div>
    </div>
  </section>
  <!-- ================> Page header end here <================== -->











<!-- ===============>> Service section start here <<================= -->
<section class="service padding-top padding-bottom">
    
    <div class="container text-dark">
        <div class="service__wrapper">
            <div class="row">
                <div class="col-sm-10 col-md-10 col-lg-10 m-auto">
                    <div class="service__item" data-aos="fade-up" data-aos-duration="800">
                        <div class="service__item-inner ">
                            <h5 class="mb-15">THIS AGREEMENT CONTAINS VERY IMPORTANT INFORMATION REGARDING YOUR RIGHTS AND OBLIGATIONS, AS WELL AS CONDITIONS, LIMITATIONS AND EXCLUSIONS THAT MIGHT APPLY TO YOU. PLEASE READ IT CAREFULLY. </h5>
                            <p class="mb-0 ">These Terms of Service and any amendments and restatements hereof (the “Agreement”) form a legal agreement covering the provision of services from Shrines to you, including offering a marketplace to enable buyers and sellers of “Digital Assets” (such term to be broadly understood to include digital currencies and gift cards such as Bitcoin, Tether, Itunes and others, supported by a Tradeshrine wallet) to engage in transactions with each other (the Company”), offering hosted digital wallet services, holding and releasing Digital Assets as done upon completion of a purchase of Digital Assets and any other services described in this Agreement (collectively the “Services” and individually, a “Service”) provided by Bobis Resources Ltd. and all of its affiliates (collectively, “Tradeshrine” or “we” or “us” or the “company”) to you as an individual (also referred to as a “user” or “you”). TradeShrine.com and its related Services are owned and operated by Tradeshrine. Your use of the Services will be governed by this Agreement, along with our Privacy Policy and other policies posted on WebSite, and E-Sign Consent.</p>
                            <br>

                            <h5 class="mb-15">THESE TERMS REQUIRE THE USE OF ARBITRATION TO RESOLVE DISPUTES RATHER THAN JURY TRIALS OR CLASS ACTIONS.</h5>
                            <p>By signing up to use an account through Tradeshrine.com, or any associated websites, APIs, or mobile applications, including any URLs operated by Tradeshrine (collectively the “Tradeshrine Website” or the “Website”), you agree that you have carefully and thoroughly read, understand, and accept all of the terms and conditions contained in this Agreement including our Privacy Policy, Cookie Policy, Partner Program Terms and Conditions and E-Sign Consent.</p>

                            <h5>THE VALUE OF DIGITAL ASSETS CAN GO UP OR DOWN AND THERE CAN BE A SUBSTANTIAL RISK THAT YOU LOSE MONEY BUYING, SELLING, HOLDING, OR INVESTING IN DIGITAL ASSETS. YOU SHOULD CAREFULLY CONSIDER WHETHER TRADING OR HOLDING DIGITAL ASSETS IS SUITABLE FOR YOU IN LIGHT OF YOUR FINANCIAL CONDITION.</h5>

                            <h5>About Tradeshrine and its Services</h5>
                            <p>TradeShrine is a leading payment and financial education marketplace and space that facilitate the purchase and sale of Digital Assets with the company accepting more than 3 different  foreign and local payment methods in exchange for their Digital Assets and of their currency. Payment methods are non-negotiable and exchanged on a direct basis between the users in the Marketplace (“Buyers”) and company  in the Marketplace (“Sellers”). Our users agree upon which payment methods to use to complete a transaction and are fully responsible and liable for using such payment methods in a lawful manner.
                                
                            </p>
                            <p>Through our Website and mobile application (“Platform”) our Users are able to request  to either buy or sell Digital Assets in a variety of convenient payment methods. A User can select a Sell Digital Asset offer (then the offer displayed is the Seller) or a Buy Digital Asset offer (then the offer creator is the Buyer). The offer maker (company)  is responsible for listing the terms of the transaction, including the payment methods the offer taker will accept. Once an offer is selected by Tradeshrine’s  User, the Seller’s Digital Assets are confirmed within a timeframe stipulated on the offer page, locked as part of our transaction procedures until all conditions necessary to consummate the transaction have occurred. The user (seller or buyer)  can reach the company  through the support button that is always active once the user enters the website or (platform). </p>
                            <p>The Digital Assets are unlocked and released to the Buyer by the Company once the Buyer has completed the terms of the transaction and payment has been confirmed valid and received by the Company. Tradeshrine WILL NOT BE HELD ACCOUNTABLE FOR A  FAILED PAYMENT. IF A USER DO NOT RECEIVE PROCEED AFTER COMPANY MADE PAYMENT TO A USER SELECTED PAYMENT METHOD THEY SHOULD GO AND RECTIFY WITH THEIR BANKS. ALL LIABILITY FOR SENDING AND RECEIVING FAILED PAYMENT LIES ON THE USER AND CONFIRMING THE VALIDITY OF THE TRANSACTIONS LIES ON THE COMPANY.</p>
                            <p>The Digital Assets that are held in locked status are released back to the user if the company chooses to cancel or decline the transaction base on their sole description. The user may not cancel the transaction at any point. The user only has the option to upload valid and unadulterated evidence of payment before company can complete the transaction. This measure is in place to safeguard the User’s and company security. Transactions on our Website and Platform are solely between users and Tradeshrine.</p>
                            <p>Tradeshrine offers a secure method of storing, sending, and receiving Digital Assets. Tradeshrine provides incidental custody of Digital Assets. Digital Assets are always stored on the blockchain in Digital Wallets managed by Tradeshrine. All Digital Assets transactions occur within the Digital Assets network. There are no guarantees that the transaction will be processed on the Digital Assets network. Tradeshrine reserves the right to refuse to process any transaction if required by law or if we deem the transactions to be against our terms and conditions in this Agreement. You hereby accept and acknowledge that you take full responsibility for all activities that occur under your account and accept all risks of any authorized or unauthorized access to your account, to the maximum extent permitted by law. The real-time holdings of your Digital Assets can also be viewed in your Wallet.</p>

                            <h5>1. GENERAL</h5>
                            <ol type="a">
                                <li>a. We reserve the right to amend, modify, change or revise this Agreement at any time, in our sole and absolute discretion and without prior notice. Any such changes in respect of your use of the Services will take effect when posted on the Tradeshrine Website and not retroactively. If you have supplied us with an email address, we may also notify you by email that the Agreement has been revised. If you do not agree to the terms of the revised Agreement, your sole and exclusive remedy is to promptly terminate your use of the Services and close your account.</li>
                                <li>b. It is your responsibility to read the Agreement carefully and periodically review this Agreement as posted on the Tradeshrine Website. Your continued use of the Services shall signify your acceptance to be bound by the then-current Agreement.</li>
                                <li>c. Failure or delay by Tradeshrine in enforcing or partially enforcing any provision of the Agreement shall not be construed as a waiver of any of our rights or remedies.</li>

                            </ol>
                            <h5>2. ACCOUNT & REGISTRATION</h5>
                            <ol type="a">
                                <li>a. In order to use the Services, you will need to register an account through our Website. During the registration process, we will ask you for certain information, including but not limited to, your name, contacts, address and other personal information to verify your identity. We may, in our sole and absolute discretion, refuse to maintain an account for you. You hereby accept and acknowledge that you: (a) are of legal age in your respective jurisdiction to agree to this Agreement; and (b) have not previously been suspended or removed from using our Services.</li>
                                <li>b. By using your account, you agree and represent that you will use our Services for yourself and you may not use your account to act as an intermediary or broker for any other third party, person or entity. Unless expressly authorized by Tradeshrine, you are only allowed to have one account and are not allowed to sell, borrow, share or otherwise make available your account or any detail necessary to access your account to people or entities other than yourself. You are solely responsible and liable for maintaining adequate security and control of any and all usernames, email addresses, passwords, two-factor authentication codes or any other codes or credentials that you use to access the Services. Your account must not contain misleading or fraudulent information. Creating false information for your account, falsifying your country of origin or providing fraudulent identification documents is strictly prohibited.</li>
                                <li>c. During the registration of your account, you agree to provide us with the information we request for the purposes of identity verification and the detection of money laundering, terrorist financing, fraud, or any other financial crime and permit us to keep a record of such information. You will need to complete certain verification procedures before you are permitted to use the Services, which procedures may be modified as a result of information collected about you on an ongoing basis. The information we request may include certain personal information, including, but not limited to, your name, address, telephone number, e-mail address, date of birth, social security number, taxpayer identification number, and a government identification. In providing us with this or any other information that may be required, you confirm that all of the information is true, accurate and not misleading. You agree to promptly keep us updated if any of the information you provide changes. YOU AUTHORIZE US TO MAKE INQUIRIES, WHETHER DIRECTLY OR THROUGH THIRD PARTIES, THAT WE CONSIDER NECESSARY TO VERIFY YOUR IDENTITY OR PROTECT YOU AND/OR US AGAINST FRAUD OR OTHER FINANCIAL CRIME, AND TO TAKE ACTION WE DEEM NECESSARY BASED ON THE RESULTS OF SUCH INQUIRIES. WHEN WE CARRY OUT THESE INQUIRIES, YOU ACKNOWLEDGE AND AGREE THAT YOUR PERSONAL INFORMATION MAY BE DISCLOSED TO CREDIT REFERENCE AND FRAUD PREVENTION OR FINANCIAL CRIME AGENCIES AND THAT THESE AGENCIES MAY RESPOND TO OUR INQUIRIES IN FULL.</li>
                                <li>d. If you are using the Services on behalf of a legal entity such as a corporate entity, you further represent and warrant that: (i) the legal entity is duly organized and validly existing under the applicable laws of the jurisdiction of its organization; and (ii) you are duly authorized by such legal entity to act on its behalf. A corporate-verified account is specific to that legal entity and can only be used by the person who registered it. Corporate accounts are not allowed to be shared with or used by other individuals or entities. Corporate accounts that are verified are allowed the following limited exemptions:
                                    <ul style="padding-left:12px;">
                                        <li>1. An approved corporate account may have several active user accounts at any time, provided they are all company-verified and operated by designated employees of the company that have been previously disclosed and approved by Tradeshrine in its sole and absolute discretion; <br>
                                        2. Corporate accounts may only have one active and valid request for a specific transaction at any one time and are not allowed to have multiple request for such specific transaction from their other corporate accounts.</li>
                                    </ul>
                                </li>
                                <li>e. You are solely responsible for creating a strong password and maintaining adequate security and control of any and all IDs, passwords, hints, personal identification numbers (PINs), API keys or any other codes that you use to access our Services. Any loss or compromise of the foregoing information and/or your personal information may result in unauthorized access to your account by third parties and the loss or theft of any Digital Assets and/or funds associated with your account, including your linked payment methods. You are solely responsible for keeping your email address, telephone number and other contact details up to date in your account profile in order to receive any notices or alerts that we may send you. <b>You should never allow remote access or share your computer screen with someone else when you are logged on to your account. We assume no responsibility for any loss that you may sustain due to compromise of account login credentials due to no fault of Tradeshrine and/or your failure to follow or act on any notices or alerts that we may send to you.</b></li>
                                <li>f. To use our Services you may need to fulfill certain legal obligations in your country and/or state of residence. By accepting these terms in this Agreement, you confirm that you have reviewed your local laws and regulations and that you are aware of, and fulfill, any and all such obligations. Due to legal or regulatory prohibitions, we do not offer the use of our Services in certain jurisdictions. By accepting the terms in this Agreement, you confirm that you are not a resident or governed by the laws and regulations of those jurisdictions.</li>
                                <li>g. We may not make all of the Services available in all markets and jurisdictions and may restrict or prohibit the use of all or a portion of the Services from certain jurisdictions (“Restricted Jurisdictions”). At this time, Restricted Jurisdictions include those that are identified on our “List of Banned Countries”, the United Arab Emirates, United States of America, Japan, United Kingdom and Canada. You must not attempt to use our Services if you are located in any of those Restricted Jurisdictions. You must not attempt to circumvent any restrictions imposed via the Services, such as by obscuring your IP address or submitting any inaccurate information regarding your location.</li>
                            </ol> <br>
                            <h5>3. JURISDICTION, ARBITRATION & SEVERABILITY</h5>
                            <p>a. This Agreement and your use of the Website and Services shall be governed by and construed in accordance with the laws of Panama, without regard to principles of conflict of laws.</p>
                            <p>b. Arbitration. You and Tradeshrine agree that any dispute arising out of or relating to this Agreement or the Services shall be finally settled in binding arbitration, on an individual basis, in accordance with The Center of Arbitration and Conciliation of Panama rules for arbitration (accessible at https://cecap.com.pa/en/reglamento-de-cecap/). Subject to applicable jurisdictional requirements, consumer claimants (individuals whose transaction is intended for personal, family, or household use) may elect to pursue their claims in their local small-claims court rather than through arbitration so long as their matter remains in small-claims court and proceeds only on an individual (non-class or non-representative) basis. CLASS ACTION WAIVER: TO THE EXTENT PERMISSIBLE BY LAW, ALL CLAIMS WILL ONLY BE BROUGHT ON AN INDIVIDUAL BASIS, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE ACTION, OR REPRESENTATIVE PROCEEDING (COLLECTIVELY “CLASS ACTION WAIVER”). THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S CLAIMS OR ENGAGE IN ANY CLASS ARBITRATION. YOU ACKNOWLEDGE THAT, BY AGREEING TO THESE TERMS, YOU AND TRADESHRINE ARE EACH WAIVING ANY RIGHT TO A TRIAL BY JURY AND YOU ARE WAIVING THE RIGHT TO PARTICIPATE IN A CLASS ACTION AGAINST TRADESHRINE. If the arbitrator(s) or arbitration administrator would impose filing fees or other administrative costs on you, we will reimburse you, upon request, to the extent such fees or costs would exceed those that you would otherwise have to pay if you were proceeding instead in a court. We will also pay additional fees or costs if required to do so by the arbitration administrator’s rules or applicable law. Apart from the foregoing, each party will be responsible for any other fees or costs, such as attorney fees that the party may incur.</p>
                                <p>c. If any part of this Agreement is held by any arbitrator or court of Panama to be invalid or unenforceable in whole or in part, the validity or enforceability of the other sections of these terms and conditions shall not be affected. Any headings contained in this Agreement are for informational purposes only and are not enforceable provisions of this Agreement.</p>

                                <h5>4. PRIVACY POLICY & SECURITY</h5>
                                <p>a. We endeavor to take all reasonable steps to protect your personal information. However, we cannot guarantee the security of any data you disclose online. You accept the inherent security risks of providing information and dealing online over the Internet and will not hold us responsible for any breach of security unless this is due to our negligence.</p>
                                <p>b. Please request in writing via support  our official privacy statement. </p>
                                <h5>5. NO WARRANTY, LIMITATION OF LIABILITY & ASSUMPTION OF RISK</h5>
                                <p>a. THE SERVICES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT ANY GUARANTEES, REPRESENTATIONS OR WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, TRADESHRINE SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND/OR NON-INFRINGEMENT. TRADESHRINE DOES NOT MAKE ANY REPRESENTATIONS OR WARRANTIES THAT ACCESS TO THE WEBSITE, ANY PART OF THE SERVICES, OR ANY OF THE MATERIALS CONTAINED THEREIN, WILL BE CONTINUOUS, UNINTERRUPTED, TIMELY, OR ERROR-FREE. TRADESHRINE IS NOT LIABLE FOR ANY DISRUPTION OR LOSS A USER MAY SUFFER. YOU HEREBY ACKNOWLEDGE AND AGREE THAT YOU HAVE NOT RELIED UPON ANY OTHER STATEMENT OR UNDERSTANDING, WHETHER WRITTEN OR ORAL, WITH RESPECT TO YOUR USE AND ACCESS OF THE SERVICES AND WEBSITE. WITHOUT LIMITING THE FOREGOING, YOU HEREBY ACKNOWLEDGE AND ACCEPT THE VARIOUS RISKS INHERENT TO USING DIGITAL CURRENCY GIFT CARDS AND DIGITAL TRAINING AND INFORMATION INCLUDING BUT NOT LIMITED TO HARDWARE FAILURE, SOFTWARE ISSUES, INTERNET CONNECTION FAILURE, MALICIOUS SOFTWARE, THIRD PARTY INTERFERENCE LEADING TO LOSS OR LACK OF ACCESS TO YOUR ACCOUNT OR WALLET AND OTHER USER DATA, SERVER FAILURE OR DATA LOSS. YOU ACCEPT AND ACKNOWLEDGE THAT TRADESHRINE WILL NOT BE RESPONSIBLE FOR ANY COMMUNICATION FAILURES, DISRUPTIONS, ERRORS, DISTORTIONS, OR DELAYS YOU MAY EXPERIENCE WHEN USING THE SERVICES, HOWEVER CAUSED.</p>
                                <p>b. IN NO EVENT SHALL TRADESHRINE, ITS AFFILIATES AND SERVICE PROVIDERS, OR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, AGENTS, EMPLOYEES, ADVISORS, CONSULTANTS OR REPRESENTATIVES, BE LIABLE (A) FOR ANY AMOUNT GREATER THAN THE VALUE OF TOTAL FEES PAID BY YOU FOR THE SERVICE THAT IS SUBJECT OF THE CAUSE OF ACTION IN THE TWELVE (12) MONTHS PRIOR TO THE LOSS ARISING OR (B) FOR ANY LOST PROFITS, DIMINUTION IN VALUE OR BUSINESS OPPORTUNITY, ANY LOSS, DAMAGE, CORRUPTION OR BREACH OF DATA OR ANY OTHER INTANGIBLE PROPERTY OR ANY SPECIAL, INCIDENTAL, INDIRECT, INTANGIBLE, OR CONSEQUENTIAL DAMAGES, WHETHER BASED IN CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE, ARISING OUT OF OR IN CONNECTION WITH AUTHORIZED OR UNAUTHORIZED USE OF THE SITE OR THE SERVICES, OR THIS AGREEMENT, EVEN IF AN AUTHORIZED REPRESENTATIVE OF TRADESHRINE HAS BEEN ADVISED OF OR KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES, AND NOTWITHSTANDING THE FAILURE OF ANY AGREED OR OTHER REMEDY OF ITS ESSENTIAL PURPOSE, EXCEPT TO THE EXTENT OF A FINAL JUDICIAL DETERMINATION THAT SUCH DAMAGES WERE A RESULT OF TRADESHRINE’S GROSS NEGLIGENCE, FRAUD, WILLFUL MISCONDUCT OR INTENTIONAL VIOLATION OF LAW. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
                                <p>c. We do not own or control the underlying software protocols which govern the operation of Digital Assets and online classes. Generally, the underlying protocols are open source, and anyone can use, copy, modify, and distribute them. We assume no responsibility for the operation of the underlying protocols and we are not able to guarantee the functionality or security of network operations. In particular, the underlying protocols may be subject to sudden changes in operating rules (including “forks”). Any such material operating changes may materially affect the availability, value, functionality, and/or the name of such digital currency cards or classes. Tradeshrine does not control the timing and features of these material operating changes. It is your responsibility to make yourself aware of upcoming operating changes and you must carefully consider publicly available information and information that may be provided by Tradeshrine in determining whether to continue to use the Services. In the event of any such operational change, Tradeshrine reserves the right to take such steps as may be necessary to protect the security and safe operation of its platform, including temporarily suspending operations for the involved digital currency(ies) card (s) or classes, and other necessary steps. Tradeshrine will use its reasonable efforts to provide you notice of its response to any material operating change; however, such changes are outside of our control and may occur without notice to Tradeshrine. Our response to any material operating change is subject to our sole discretion and includes deciding not to support any new fork or other actions. You acknowledge and accept the risks of operating changes to Digital Assets’ protocols and agree that Tradeshrine is not responsible for such operating changes and not liable for any loss of value you may experience as a result of such changes in operating rules. You acknowledge and accept that Tradeshrine has sole discretion to determine its response to any operating change and that we have no responsibility to assist you with unsupported currencies or protocols.</p>
                                <p>d. In using our Services, you may view content or utilize Services provided by third parties, including hyperlinks to third-party websites and services of such parties (“3rd party content”). We do not endorse, adopt or control any 3rd party content and will have no responsibility or liability for such 3rd party content whatsoever. In addition, your dealings or correspondence with such third parties are solely between you and the third parties. We are not responsible or liable for any loss or damage of any sort incurred as a result of any such dealings and you understand that your use of 3rd party content, and your interactions with third parties, is solely at your own risk.</p>
                                <p>e. For the avoidance of doubt, Tradeshrine does not provide investment, tax, or legal advice. Tradeshrine does not offer securities services or investment advice. All transactions through our Marketplace are conducted on a onsite basis between the user and Tradeshrine and you are solely responsible for determining whether any investment, investment strategy or related transaction is appropriate for you based on your personal investment objectives, financial circumstances and risk tolerance. You should consult your legal or tax professional regarding your specific situation. From time to time, we may provide educational information about our platform and products, in order to assist users in learning more about our Services and how to succeed in trading. Information may include, but is not limited to, blog posts, articles, links to 3rd party content, news feeds, tutorials, and videos. The information provided on the Website or any third-party sites does not constitute investment advice, financial advice, trading advice, or any other sort of advice, and you should not treat any of the Website’s content as such. Before making the decision to buy, sell or hold learn or any Digital Assets, you should know WE DO NOT REFUND PAYMENT and you  should conduct your own due diligence and consult your financial advisors before making any investment decision. Tradeshrine will not be held responsible for the decisions you make to buy, sell, learn or hold Digital Assets based on the information provided by Tradeshrine. The price of the Digital Assets displayed on the website is based on the exchange rates acquired from public data sources and may not reflect the value of such assets.</p>
                                <p>f. You agree that we are not liable for any price fluctuations in Digital Assets. In the event of market disruption or a Force Majeure event (as described below), we may do one or more of the following: (a) suspend access to the Services; or (b) prevent you from completing any actions via the Services. We will not be liable for any losses suffered by you resulting from such actions. Following any such event, when Services resume, you acknowledge that prevailing market rates may differ significantly from the rates available prior to such event.</p>
                                <p>g. We make no warranty that the Website, or the server that makes it available, are free of viruses or errors, that its content is accurate, that it will be uninterrupted, or that defects will be corrected. We will not be responsible or liable to you for any loss of any kind, from action taken, or taken in reliance on material, or information, contained on the Website.</p>
                                <h5>6. RELEASE OF TRADESHRINE & INDEMNITY</h5>
                                <p>a. If you have a dispute with one or more of our Services, you release Tradeshrine, its affiliates and service providers, and each of its or their respective officers, directors, employees, agents and representatives, from any and all claims, demands and damages (actual and consequential) of every kind and nature arising out of or in any way connected with such disputes. You agree to indemnify and hold Tradeshrine, its affiliates and each of its or their respective officers, directors, employees, agents and representatives, harmless from any claim or demand (including attorneys’ fees and any fines, fees or penalties imposed by any regulatory authority) arising out of or related to your breach of this Agreement or your violation of any law, rule or regulation, or the rights of any third party.</p>
                                <h5>7. TRANSACTIONS ON TRADESHRINE PLATFORM’S & MARKETPLACE</h5>
                                <p>a. The Website allows users to solicit offers to buy or sell Digital Assets learn how to trade and gets trading signals. When a user initiates a transaction for the purchase or sale of Digital Assets and learning how to trade and or getting a trade signal, the transaction is consummated pursuant to this Agreement and to the additional terms, if any, detailed by the user or the user’s counterparty. The following general terms apply to each transaction described below:</p>

                                <p style="margin-left: 12px;">1. Buying Digital Assets via soliciting an offer:
                                <ul>
                                    <li>a. When purchasing Digital Assets on Tradeshrine’s Marketplace, there are no fees for Tradeshrine as part of a transaction that is payable by us on our Marketplace the fees of Tradeshrine are paid by the Seller, buyers and users.</li>
                                    <li>b. Each offer will vary in exchange rate, speed of exchange, and other terms and conditions imposed by Tradeshrine and no user should use any ANY CRYPTOCURRENCY RELATED LANGUAGE ON THE PAYMENT DESCRIPTION TO MAKE PAYMENT OTHERWISE THE CORRESPONDING ASSETS WILL NOT BE RELEASED TO THE USER. By accepting our offer, the offer user agrees to be bound by the terms and conditions of that offer. The terms and conditions specified by the company are valid in all cases except when they contradict or violate this Agreement, are illegal, are unreasonable or otherwise difficult to comply with (as determined in Tradeshrine sole and absolute discretion)</li>
                                    <li>c. . IT IS THE USER’S RESPONSIBILITY TO CAREFULLY READ THIS TERMS AND CONDITIONS  AND FOLLOW THEM EXACTLY. TRADESHRINE  MUST NOT MAKE THE PAYMENT UNLESS THE USER HAS FOLLOWED ALL TERMS AND CONDITIONS LISTED HERE. IF THE USER SUBMITS PAYMENT WITHOUT FOLLOWING THE TERMS AND CONDITIONS, TRADESHRINE CANNOT ASSIST THE BUYER IN A DISPUTE OR RESOLUTION PROCESS.</li>
                                    <li>d. Payment verification and the responsibility to  to unlock Digital Assets rest solely with the user when selling to Tradeshrine. If the seller having issues sending assets or verifying payment, Tradeshrine's support team will then review and resolve the issue where applicable.</li>
                                </ul>
                                </p>
                                <p style="margin-left: 12px;">2. Selling Digital Assets. </p>
                                <p style="margin-left: 12px;">3. When Selling Digital Assets on the Tradeshrine Marketplace (platform): 
                                        <ul>
                                            <li>a. Tradeshrine must verify and process the payment in a reasonable amount of time, and within a certain amount of time as specified in the offer terms. Once the Buyer has submitted payment to the us in accordance with the offer terms, it is the our  sole duty and responsibility to promptly verify and process the payment and then unlock the Digital Assets from Tradeshrine and release it to the Buyer.</li>
                                            <li>b.  Tradeshrine charges a fee to the Seller and buyer of Digital Assets for locking Digital Assets in Tradeshrine subject to a sale. Unless determined otherwise in Tradeshrine’s sole and absolute discretion, Tradeshrine shall not reimburse any losses to the Seller or buyer whether due to a violation of this Agreement, fraud, or otherwise, and our fee will not be refunded under any circumstances except trade cancellation. </li>
                                            <li>c. Any advertisement of any type of external service in any section of Tradeshrine Marketplace or page that would facilitate buying or selling Digital Assets outside of Tradeshrine Services is strictly prohibited.</li>
                                        </ul>
                                </p>
                                <p style="margin-left: 12px;">Compliance </p>
                                <p>a. Tradeshrine and the Services are not affiliated or associated with, nor endorsed or sponsored by any third party, including but not limited to any gift card issuer. Designated trademarks, brands, and other identifiers are solely the property of their respective owners. Tradeshrine and its Services are not endorsed, sponsored, associated or affiliated in any way by or with such owners.</p>
                                <p>b. Tradeshrine is not a licensed gift card or cryptocurrency vendor or authorized dealer of any gift card or currency  issuer. Any gift cards you receive or send  directly to us by a user using the Tradeshrine Marketplace are subject to the terms and conditions of the third-party merchant with whom it is redeemable (“Issuer”). Tradeshrine is not responsible for the acts or omissions of any Issuer(s), or any fees, expiration dates, penalties or terms and conditions associated with the Issuer’s gift card or coins received using the Tradeshrine Marketplace. By receiving or sending the gift card or crypto from or to a user, you acknowledge that you have read the gift card’s terms and conditions, and represent to Tradeshrine that you are eligible to use such gift cards and cryptocurrency under the gift card and crypto third party platform’s  terms and conditions, or under applicable law.</p>
                                <p>c. BROKERING OR RESELLING OF GIFT CARDS IS STRICTLY PROHIBITED ON OUR WEBSITE AND MARKETPLACE. YOU MUST BE THE RIGHTFUL OWNER OF THE GIFT CARD AND AT TRADESHRINE’S REQUEST YOU AGREE TO PROVIDE TRADESHRINE WITH VALID PROOF OF OWNERSHIP OF YOUR GIFT CARD (SUCH AS A RECEIPT). TRADESHRINE MAKES NO CLAIM, REPRESENTATION OR GUARANTEE THAT ANY THIRD-PARTY PAYMENT METHODS ON THE WEBSITE PERMIT TRANSACTIONS VIA TRADESHRINE’S SERVICE, OR THAT ANY THIRD-PARTY PAYMENT METHODS ON OUR WEBSITE SUPPORT OR ARE SUPPORTED BY OUR SERVICES. YOU SHOULD NOT USE SUCH THIRD-PARTY PAYMENT METHODS WITH TRADESHRINE IF SUCH THIRD-PARTY DOES NOT PERMIT IT.</p>
                                <p>d. YOU ARE WHOLLY RESPONSIBLE TO COMPLY WITH ALL LAWS AND REGULATIONS FOR THE JURISDICTION(S) IN WHICH YOUR TRANSACTION TAKES PLACE.</p>
                                <p>e. All transactions must take place within Tradeshrine. Taking transactions outside the Tradeshrine platform or exchanging external contact details are strictly prohibited.</p>

                                <!-- add 5 - 12 -->
                                <div class="left-12">
                                    <p>5. <b>Transfer Limitations</b>. We may, in our sole discretion, impose limitations or restrictions on the size, type, or manner of any proposed transfer transactions, such as a limit on the total amount of Digital Assets that may be posted for sale.</p>
                                    <p>6. <b>No Guarantee</b>. Tradeshrine does not guarantee that you will be able to sell Digital Assets on its Marketplace. The act of buying or selling Digital Assets via Tradeshrine’ Marketplace does not guarantee that you will be able to buy or sell Digital Assets via the Marketplace at a later time.</p>
                                    <p>7. <b>Relationship</b>. Nothing in this Agreement is intended to nor shall create any partnership, joint venture, agency, consultancy, or trusteeship, you and Tradeshrine being with respect to one another independent contractors.</p>
                                    <p>8. <b>Accuracy of Information</b>. You represent and warrant that any information you provide via the Services is accurate and complete. You accept and acknowledge that Tradeshrine is not responsible for any errors or omissions that you make in connection with any transaction initiated via the Services, for instance, if you mistype a Wallet address or otherwise provide incorrect information. We strongly encourage you to review your transaction details carefully before completing them via the Services.</p>
                                    <p>9. No Cancellations or Modifications; Wallet Activities. Once transaction details have been submitted to the digital currency network via the Services, Tradeshrine cannot assist you with canceling or otherwise modifying your transaction. Tradeshrine has no control over any digital currency network and does not have the ability to facilitate any cancellation or modification requests. Tradeshrine does not store or custody any locked Digital Assets. Digital Assets are always recorded on their respective networks or blockchains. All digital currency transactions occur within the digital currency network, not on Tradeshrine. There are no guarantees that the transaction will process on the digital currency network. Tradeshrine reserves the right to refuse to process any transaction if required by law or if we deem the transactions to be against our terms and conditions in this Agreement. You hereby accept and acknowledge that you take full responsibility for all activities that occur under your Wallet and accept all risks of any authorized or unauthorized access to your Wallet, to the maximum extent permitted by law.</p>
                                    
                                    <p>10. Taxes. It is your responsibility to determine what, if any, taxes apply to the transactions for which you have submitted transaction details via the Services, and it is your responsibility to report and remit the correct tax to the appropriate tax authority. You agree that Tradeshrine is not responsible for determining whether taxes apply to your digital currency transactions or for collecting, reporting, withholding or remitting any taxes arising from any digital currency transactions.</p>
                                    <p>11. User Reputation. When you engage in a Transaction, we allow use every necessary measure and technicality to record and ascertain compliance  on your interaction with our company or services. We also reserves the full right to suspend your account we believe you have or trying to  violate this Agreement in any way. These reports are confidential, but we may use them in connection with a dispute as described in Section 8.</p>
                                    <p>12. Transaction History. You may view your transaction history through your Account. You agree that the failure of the Services to provide such confirmation shall not prejudice or invalidate the terms of such transaction.</p>
                                    <p>13. Returns, Refunds. When you purchase a good or service from a third party using your Account or when you make payment for your trading class or signal, it is final. We do not process refunds or returns.</p>
                                    <p>14. Tradeshrine charges fees for Services, applicable fees will be displayed prior to you using any Service to which a fee applies. Request to see “Tradeshrine  Fees” for further details via support. Our fees are subject to change and Tradeshrine reserves the right to adjust its pricing and fees and at any time.</p>

                                    <br>
                                    <h5>8. DISPUTING TRANSACTIONS VIA TRADESHRINE’S DISPUTE RESOLUTION PROCESS</h5>
                                    <p>a. Disputing Transactions. In most cases, the easiest way to settle a dispute is for user to communicate and write to support immediately, work together to figure out what happened, and come to an agreeable solution. When a user and Tradeshrine’s support team cannot come to an agreeable solution, Tradeshrine’ compliance team (“Tradeshrine Compliance”) can help through escalation of matter to our official email or verified handles.</p>
                                    <p>b. Dispute Resolution Process. Below are the steps Tradeshrine Support takes in the event of a dispute.</p>
                                    <p style="margin-left: 24px;">1. <b>*Initiation*</b> Upon initiating a dispute, respond to the type of dispute from the options of questions presented and describe the issue leading to your dispute. Users will have their own set of options.The list of most common options presented for describing your dispute would be communicated to you during your filing session. <br>
                                        2. <b>*Notification*</b> Once a dispute has been submitted, Tradeshrine Support will provide the compliance team with notification by email and by sending a message directly if found out it's a case outside their jurusdiction. <br>
                                        
                                        3. <b>*Response*</b> Review the dispute and provide Tradeshrine Support with an explanation of what happened. Include any evidence you have to support your explanation, such as proof of payment, proof of ownership or proof that you have or have not received payment.
                                        4. Tradeshrine *Review* Disputed transactions will be investigated by Tradeshrine Support and a decision will be made based upon available evidence and data provided by user and/or collected by the dispute team or lack thereof. Tradeshrine  Support resolves disputes by evaluating various factors as described below.</p>
                                        <p>c. Dispute Review. During a dispute review, Tradeshrine Support may give you instructions that you are required to follow. The instructions given to you may require you to provide additional evidence, such as additional ID verification, proof of payment, any photo, audio, or video evidence, or any other documents deemed relevant by Tradeshrine and may require you to provide such evidence within a specified timeframe. Failure to follow the instructions may lead to the dispute being resolved against you. Tradeshrine Support will typically provide notice of its decision via the chat or to your email within 7 days of receiving the dispute, but under some circumstances, it may take longer.</p>
                                        <p>d. Unresponsiveness When you are involved in a transaction, it is important that you remain active and available from the time the transaction is started to the time that the transaction is completed, canceled, or resolved. This means that you must be able to provide a response to a request by Tradeshrine Support in a disputed transaction within the time specified by Tradeshrine Support or you may be deemed as unresponsive and the dispute may be resolved against you..</p>
                                        <p>e. Dispute Resolution A disputed transaction is most commonly resolved by Tradeshrine Support. </p>
                                        <p>f. If the user of a disputed transaction provides fraudulent information or fraudulent documents or makes false claims or otherwise uses deceptive tactics, the dispute may be immediately resolved against such user and such user’s account may be immediately suspended or terminated at the sole discretion of Tradeshrine Support. </p>
                                        <p>g. Appeal. If you believe Tradeshrine has resolved a dispute in a way which is not in accordance with this Agreement, you have a right to request an appeal. To request an appeal, you need to promptly notify us via the official email no later than 10 calendar days after notice of Tradeshrine Support’s decision is delivered to you and provide us with sufficient details and evidence supporting your case for request. Your appeal should specifically identify how you believe Tradeshrine incorrectly resolved the dispute as per the terms of this Agreement and provide evidence of such incorrect decision. Please be reminded that whether during the dispute process or generally any time when using our Services, you are obligated to keep a civil tone and be respectful to Tradeshrine Support. See generally, “Section 13 - Prohibited Use”.</p>
                                        <p>h. Finality. You acknowledge and agree that Tradeshrine’ decision regarding a dispute after the appeal is conclusive, final and binding as described in this Agreement. Tradeshrine will have no liability to a user in connection with its decisions.</p>

                                        <br>
                                        <h5>9. FEES FOR USING TRADESHRINE SERVICES</h5>
                                        <p>a. Creating a Wallet/Account is free. Tradeshrine charges fees for Services, applicable fees will be displayed prior to you using any Service to which a fee applies. Request to see “Tradeshrine  Fees” for further details. Our fees are subject to change and Tradeshrine reserves the right to adjust its pricing and fees and at any time.</p>
                                        <br>
                                        <h5>10. NO RIGHT TO CANCEL SERVICES OR MINERS FEES</h5>
                                        <p>a. If you use a Service to which a charge applies, or you initiate a transaction or request with a miners fee via the Services, you will not be eligible for a refund or reimbursement once you have confirmed that you wish to proceed with the Service or transaction.</p>
                                        <br>
                                        <h5>11. DISCONTINUANCE OF SERVICES</h5>
                                        <p>a. We may, in our sole discretion and without cost to you, with or without prior notice and at any time, modify or discontinue, temporarily or permanently, any portion of our Services.</p> <br>
                                        <h5>12. SUSPENSION OR TERMINATION OF SERVICES & ACCOUNT; LIMITING ACCESS TO YOUR WALLET</h5>
                                        <p>a. We may in our sole and absolute discretion, immediately and without prior notice: (a) suspend, restrict, or terminate your access to any or all of the Services (including limiting access to your Wallet), and/or (b) deactivate or cancel your account if: (i) we are so required by applicable law, a facially valid subpoena, court order, or binding order of a government authority; (ii) we reasonably suspect you have or may act in violation of this Agreement; (iii) use of your account is subject to any pending litigation, investigation, or government proceeding and/or we perceive a heightened risk of legal or regulatory non-compliance associated with your account activity; (iv) our service partners are unable to support your use; (v) you take any action that we deem as circumventing our controls and procedures or (vi) we think it is necessary to do so to protect us, our users, including you, or our employees from danger or loss. If we exercise our rights to limit or refuse your access to the Services, we will not be responsible for any consequences of our refusal to give you access to the Services, including any delay, damage or inconvenience you may suffer as a result.</p>
                                        <p>b. If we suspend or close your account, terminate your use of the Services for any reason, or limit access to your Wallet, we will attempt to provide you with notice of our actions unless a court order or other legal process prohibits us from providing you with such notice. YOU ACKNOWLEDGE THAT OUR DECISION TO TAKE CERTAIN ACTIONS, INCLUDING LIMITING ACCESS TO, SUSPENDING, OR CLOSING YOUR ACCOUNT OR WALLET, MAY BE BASED ON CONFIDENTIAL CRITERIA THAT ARE ESSENTIAL TO OUR RISK MANAGEMENT AND SECURITY PROTOCOLS. YOU AGREE THAT TRADESHRINE IS UNDER NO OBLIGATION TO DISCLOSE THE DETAILS OF ITS RISK MANAGEMENT AND SECURITY PROCEDURES TO YOU. In the event that we suspend your account or access to your Wallet, we will remove the suspension as soon as possible once the reasons for the suspension no longer exist, however we are under no obligation to notify you as to when (if ever) such suspension will be removed.</p>
                                        <p>c. If you are holding Digital Assets in your Tradeshrine Wallet and there has been no activity in your account for a period of time prescribed by applicable law, we may be required to report such remaining Digital Assets in your account as unclaimed property in accordance with abandoned property and escheat laws. If this occurs, we will use reasonable efforts to provide written notice to you. If you fail to respond to any such notice within seven (7) business days of receipt, or as otherwise required by law, we may be required to deliver any such Digital Assets to the applicable jurisdiction as unclaimed property.</p>
                                        <p>d. We reserve the right to deduct a dormancy fee or other administrative charges from such unclaimed Digital Assets as permitted by applicable law.</p>
                                        <br>
                                        <h5>13. PROHIBITED USE</h5>
                                        <p>a. When accessing or using the Services, you agree that you will use the Services in accordance with the terms and conditions in this Agreement (including the Privacy Policy) and not commit any unlawful act, and that you are solely responsible for your conduct while using our Services. Without limiting the generality of the foregoing, you agree that you will not:</p>
                                        <p style="margin-left: 24px;">1. use our Services in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying our Services, or that could damage, disable, overburden or impair the functioning of our Services in any manner; <br>
                                            2. engage in any activity which could violate, or assist in violation of, any law, statute, ordinance, or regulation, sanctions programs administered in the countries where we conduct business or operations, or which would involve proceeds of any unlawful activity; publish, distribute or disseminate any unlawful material or information; <br>
                                            3. interfere with another user’s access to or use of any of our Services; defame, abuse, extort, harass, stalk, threaten or otherwise violate or infringe the legal rights (such as, but not limited to, rights of privacy, publicity and intellectual property) of us or other users; incite, threaten, facilitate, promote, or encourage hate, racial intolerance, or violent acts against others; harvest or otherwise collect information from our Website about other users;<br>
                                            4. engage in any activity which operates to defraud, defame or otherwise cause any damage to Tradeshrine or our users; or provide any false, inaccurate, deceptive or misleading information to Tradeshrine or to another user in connection with our Services or as otherwise provided or requested pursuant to this Agreement; <br>
                                            5. introduce to the Services any virus, Trojan, worms, logic bombs or other harmful material; use any robot, spider, crawler, scraper or other automated means or interface not provided by us to access our Services or to extract data; attempt to circumvent any content filtering techniques we employ, or attempt to access any service or area of our Services that you are not authorized to access; or placement anywhere within Tradeshrine’ Marketplace of any advertisement or promotion that would facilitate buying or selling Digital Assets outside of Tradeshrine’ Services; <br>
                                            6. engage in transactions involving items that infringe or violate any copyright, trademark, right of publicity or privacy or any other proprietary right under the law, or other licensed materials without the appropriate authorization from the rights holder; use of Tradeshrine intellectual property, name, or logo, including use of Tradeshrine’ trade or service marks, without prior written consent from us or in a manner that otherwise harms Tradeshrine or the Tradeshrine brand; any action that implies an untrue endorsement by or affiliation with Tradeshrine; or develop any third-party applications that interact with our Services without our prior written consent; or <br>
                                            7. encourage or induce any third party to engage in any of the activities prohibited under this Section 13.</p>
                                            <br>
                                            <h5>14. INTELLECTUAL PROPERTY RIGHTS</h5>
                                            <p>a. We grant you a limited, nonexclusive, nontransferable license, subject to the terms and conditions in this Agreement, to access and use the Services, Website, and related content, materials, information (collectively, the “Content”) solely for purposes approved by Tradesheine from time to time. Any other use of the Website or Content is expressly prohibited and all other right, title, and interest in the Services, Website or Content is exclusively the property of Tradeshrine. You agree you will not copy, transmit, distribute, sell, license, reverse engineer, modify, publish, or participate in the transfer or sale of, create derivative works from, or in any other way exploit any of the Content, in whole or in part without the prior written consent of Tradeshrine. You may not copy, imitate or use any of Tradeshrine’ trademarks, registered marks, logos or any of its intellectual property without Tradeshrine’ prior written consent. <br>
                                            b. Although we intend to provide accurate and timely information on the Tradeshrine Website, our Website (including, without limitation, the Content) may not always be entirely accurate, complete or current and may also include technical inaccuracies or typographical errors. In an effort to continue to provide you with as complete and accurate information as possible, information may be changed or updated from time to time without notice, including without limitation information regarding our policies, products and Services. Accordingly, you should verify all information before relying on it, and all decisions based on information contained on the Tradeshrine Website are your sole responsibility and we shall have no liability for such decisions. Information provided by third parties is for informational purposes only and Tradeshrine makes no representations or warranties to its accuracy. Links to third-party materials (including without limitation, websites) may be provided as a convenience but are not controlled by us. You acknowledge and agree that we are not responsible for any aspect of the information, content, or Services contained in any third-party materials or on any third-party sites accessible or linked to the Tradeshrine Website.</p>
                                            <br>
                                            <h5>15. FEEDBACK AND USER SUBMISSIONS</h5>
                                            <p>a. Tradeshrine is always seeking to improve its Services and the Website. If you have ideas or suggestions regarding improvements or additions to Tradeshrine’ Services or the Website, Tradeshrine would like to hear them; however, any submission will be subject to the terms and conditions in this Agreement. <br>
                                            b. Under no circumstances will any disclosure of any idea or feedback, or any related material to Tradeshrine or any of its subsidiaries, parents or affiliated companies, or any of their officers, directors, managers, members, shareholders, employees and agents, or any of their heirs, successors, representatives and assigns (each a “Tradeshrine Party” and collectively, the “Tradeshrine Parties”) be subject to any obligation of confidentiality or expectation of compensation.<br>
                                            c. By submitting an idea or feedback or any related material that would be subject to intellectual property rights (the “Work”) to Tradeshrine or any Tradeshrine Party, you grant to Tradeshrine, in respect of the Work submitted, a non-exclusive, perpetual, worldwide royalty free license to use all of the content of such ideas and feedback, for any purpose whatsoever. Further, you are waiving any moral rights to the fullest extent permitted under Panama law that you may have in the Work and are representing and warranting to such Tradeshrine Party that the Work are wholly original with you, that no one else has any rights in the Work and that all Tradeshrine Parties are free of any royalty to implement the Work and to use the related material if so desired, as provided or as modified by any Tradeshrine Party, without obtaining permission or license from any third party. <br>
                                            d. You further accept that Tradeshrine may sub-license any of the Tradeshrine Parties to use in any way any Work and material you have submitted. <br> 
                                            e. We have the right to remove any posting you may make to the Website, in our absolute discretion, without warning or reasons.</p>

                                            <br>
                                            <h5>16. HOW TO CONTACT US</h5>
                                            <p>We recommend you visit our FAQ page before contacting us. In the event the FAQ page does not contain the information you are looking for, Tradeshrine  offers 24/7 support. You may contact us through our support widget located on the FAQ page.</p>
                                            <br>
                                            <h5>17. FORCE MAJEURE</h5>
                                            <p>We shall not be liable for delays, failure in performance or interruption of Service which result directly or indirectly from any cause or condition beyond our reasonable control, including but not limited to, significant market volatility, any delay or failure due to any act of God, act of civil or military authorities, act of terrorists, civil disturbance, war, strike or other labor dispute, fire, interruption in telecommunications or Internet services or network provider services, failure of equipment and/or software, other catastrophe or any other occurrence which is beyond our reasonable control and shall not affect the validity and enforceability of any remaining provisions.</p>
                                            <br>
                                            <h5>18. NATURE OF AGREEMENT</h5>
                                            <p>This Agreement constitutes the entire agreement between you and Tradeshrine with respect to the subject matter of the terms and conditions in this Agreement and this Agreement cancels and supersedes any prior understandings and agreements between you and Tradeshrine as to that subject matter. You may not assign any of your rights or obligations under this Agreement without our prior written consent.</p>

                                            <br><br>
                                            <p>Tradeshrine<b> Copyright © 2024 BobisResources Limited. All Rights Reserved.“TRADESHRINE” is a trademark of BOBIS RESOURCES LTD. BobisResources LTD has no relation to MoneyGram, Western Union, Payoneer, WorldRemit, Paxum, PayPal, Amazon, OkPay, Payza, Walmart, Reloadit, Perfect Money, WebMoney, Google Wallet, BlueBird, Serve, Square Cash, NetSpend, Chase QuickPay, Skrill, Vanilla, MyVanilla, OneVanilla, Neteller, Venmo, Apple,Chipper cash, Vpay, Cryptocurrencies, ChimpChange or any other payment method. We make no claims about being supported by or supporting these services. Their respective wordmarks and trademarks belong to them alone. Official mailing address:  Zuba-Gwagwalada Express road, Nipco junction, Tungan Maje, F.C.T Abuja, Nigeria. </b></p>
                                </div>

                        </div>


                  
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</section>
<!-- ===============>> Service section start here <<================= -->

<!-- ========== Roadmap Section start Here========== -->











 <!-- ===============>> footer start here <<================= -->
 <?php include 'templates/footer.php'; ?>
 <!-- ===============>> footer end here <<================= -->




 <!-- ===============>> scrollToTop start here <<================= -->
 <a href="#" class="scrollToTop scrollToTop--home1"><i class="fa-solid fa-arrow-up-from-bracket"></i></a>
 <!-- ===============>> scrollToTop ending here <<================= -->





 <!-- vendor plugins -->

<?php include 'templates/scripts.php'; ?>


</body>
</html>